version: "3.7"

services:

    #PHP Service
    app:
      build:
        context: .
        dockerfile: Dockerfile
      image: laravelvue
      container_name: app-vue-laravel
      restart: unless-stopped
      tty: true
      environment:
        SERVICE_NAME: app
        SERVICE_TAGS: dev
      working_dir: /var/www
      ports:
        - 80:80
      volumes:
        - ./:/var/www
        - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      networks:
        - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

