version: "3.7"

services:
    # image project
    app:
        container_name: laraveltest
        build:
            context: .
            dockerfile: Dockerfile
        image: phpfpm8.1
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        ports: 
            - "8080:80"            
        networks: 
            - laravel-9

networks: 
    laravel-9:
        driver: bridge