version: "3.7"

services:
    # Car Tracking Service
    app:
        container_name: CarTrackingPlataform
        image: giurian/cartrackergps:latest
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "80:8000"
        command: bash -c 'php artisan serve --host 0.0.0.0'
        networks:
            - laravel-9

    #MySQL Service
    db:
        image: mysql:8
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
        - "3306:3306"
        environment:
            MYSQL_DATABASE: vehicletrackerdb
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_PASSWORD: toor
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - laravel-9

#Networks
networks:
    laravel-9:
        driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
